services:
  - type: web
    name: pneumonia-detector
    env: python
    plan: free

    rootDir: deploy

    buildCommand: pip install -r requirements.txt

    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port 10000

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
